export const reviewCopy = {
  zh: {
    jobsTitle: "批改任务",
    jobsIntro: "查看自己的评分批次，并进入需要教师确认的论文。",
    loading: "正在加载批次…",
    loadFailed: "暂时无法加载批次。",
    reviewLoading: "正在加载复核任务…",
    reviewLoadFailed: "暂时无法加载复核任务。",
    loadUnauthorized: "登录已失效，请重新登录后再查看批次。",
    loadServerFailed: "服务端暂时无法读取批次，请确认 API 已更新并正常运行。",
    retryLoad: "重新加载",
    emptyTitle: "还没有批改任务",
    emptyBody: "创建批次后，可在这里查看进度并完成教师复核。",
    progress: "进度",
    model: "模型",
    papers: "论文",
    needsReview: "待复核",
    completed: "已确认",
    failed: "失败",
    open: "进入复核",
    unavailable: "尚不可复核",
    batchConfirm: "确认全部已保存草稿",
    batchConfirmPrompt: "确认该批次所有已保存草稿？确认后不可修改。",
    batchUnavailable: "先逐篇保存全部待复核草稿",
    confirming: "正在确认…",
    batchSuccess: "批量确认成功。",
    batchFailed: "批量确认失败，未确认任何论文。",
    back: "返回批次",
    queue: "论文队列",
    paper: "论文正文",
    review: "评分复核",
    attempt: "模型结果",
    rubric: "评分标准",
    score: "分数",
    reason: "英文评分理由",
    suggestions: "英文修改建议（每行一条）",
    deductions: "扣分",
    applied: "应用扣分",
    feedback: "英文总体反馈",
    evidence: "证据",
    evidenceTarget: "证据归属",
    addEvidence: "添加当前选中文本",
    removeEvidence: "移除证据",
    changeReason: "修改 AI 结果的原因",
    changeReasonHint: "只要修改模型评分、理由、证据或反馈，就必须填写。",
    save: "保存草稿",
    saving: "正在保存…",
    saved: "草稿已保存。",
    regrade: "使用原模型重评",
    regradePrompt: "该论文没有可复核的成功模型结果。确认使用批次固定的原模型重评？这会产生新的模型费用。",
    regrading: "正在提交重评…",
    regradeSubmitted: "已提交原模型重评。",
    regradeFailed: "原模型重评提交失败，未创建新的评分轮次。",
    retryFailedItem: "重试评分",
    retryFailedPrompt: "确认重试这篇失败论文？这会使用批次固定模型并产生新的模型费用。",
    retryingFailedItem: "正在重试…",
    retryFailedSubmitted: "失败论文已重新排队。",
    retryFailedFailed: "失败论文重试提交失败，任务状态未改变。",
    confirm: "确认最终成绩",
    confirmWarning: "确认后不可修改或再次重评。",
    confirmPrompt: "确认该论文的最终成绩？确认后不可修改。",
    finalScore: "最终总分",
    subtotal: "维度小计",
    deductionTotal: "扣分合计",
    exactServer: "浏览器仅预览；最终分数由服务器精确重算。",
    selectionEmpty: "请先在同一个文本块中选择逐字原文。",
    selectionCrossBlock: "证据不能跨越多个文本块，请分开选择。",
    selectTarget: "请先选择证据归属的维度或扣分项。",
    actionFailed: "操作失败，请检查输入或刷新后重试。",
    conflict: "复核已被另一请求修改，请刷新后重试。",
    confirmed: "该论文已确认，内容只读。",
    noDeductions: "本评分标准没有扣分项。",
    block: "文本块",
  },
  en: {
    jobsTitle: "Grading jobs",
    jobsIntro: "Review your batches and open papers that need teacher confirmation.",
    loading: "Loading grading jobs…",
    loadFailed: "Grading jobs could not be loaded.",
    reviewLoading: "Loading the review task…",
    reviewLoadFailed: "The review task could not be loaded.",
    loadUnauthorized: "Your session expired. Sign in again to view grading jobs.",
    loadServerFailed: "The server cannot read grading jobs right now. Confirm the API is updated and running.",
    retryLoad: "Reload",
    emptyTitle: "No grading jobs yet",
    emptyBody: "Created batches will appear here for progress tracking and review.",
    progress: "Progress",
    model: "Model",
    papers: "Papers",
    needsReview: "Needs review",
    completed: "Confirmed",
    failed: "Failed",
    open: "Open review",
    unavailable: "Not ready for review",
    batchConfirm: "Confirm all saved drafts",
    batchConfirmPrompt: "Confirm every saved draft in this batch? This cannot be undone.",
    batchUnavailable: "Save every pending review draft first",
    confirming: "Confirming…",
    batchSuccess: "Batch confirmed.",
    batchFailed: "Batch confirmation failed. No papers were confirmed.",
    back: "Back to jobs",
    queue: "Paper queue",
    paper: "Paper text",
    review: "Grade review",
    attempt: "Model result",
    rubric: "Rubric",
    score: "Score",
    reason: "Grading reason in English",
    suggestions: "Revision suggestions in English, one per line",
    deductions: "Deductions",
    applied: "Apply deduction",
    feedback: "Overall feedback in English",
    evidence: "Evidence",
    evidenceTarget: "Evidence target",
    addEvidence: "Add selected text",
    removeEvidence: "Remove evidence",
    changeReason: "Reason for changing the AI result",
    changeReasonHint: "Required when any model score, reason, evidence, or feedback changes.",
    save: "Save draft",
    saving: "Saving…",
    saved: "Draft saved.",
    regrade: "Regrade with original model",
    regradePrompt: "This paper has no successful model result to review. Regrade with the batch's fixed original model? This incurs new model usage cost.",
    regrading: "Submitting regrade…",
    regradeSubmitted: "Regrade submitted.",
    regradeFailed: "The regrade was not submitted and no new scoring round was created.",
    retryFailedItem: "Retry grading",
    retryFailedPrompt: "Retry this failed paper with the batch's fixed model? This incurs new model usage cost.",
    retryingFailedItem: "Retrying…",
    retryFailedSubmitted: "The failed paper was queued again.",
    retryFailedFailed: "The retry was not submitted and the task state did not change.",
    confirm: "Confirm final grade",
    confirmWarning: "Confirmation is permanent and blocks further regrading.",
    confirmPrompt: "Confirm this final grade? It cannot be edited afterward.",
    finalScore: "Final score",
    subtotal: "Dimension subtotal",
    deductionTotal: "Deductions",
    exactServer: "Browser preview only; the server recalculates the exact final score.",
    selectionEmpty: "Select an exact quote within one text block first.",
    selectionCrossBlock: "Evidence cannot span text blocks. Select each block separately.",
    selectTarget: "Choose a rubric dimension or deduction first.",
    actionFailed: "The action failed. Check the form or refresh and try again.",
    conflict: "This review changed in another request. Refresh and try again.",
    confirmed: "This paper is confirmed and read-only.",
    noDeductions: "This rubric has no deductions.",
    block: "Block",
  },
} as const;
