export type Language = "zh" | "en";

export const copy = {
  zh: {
    mainNavigation: "主导航",
    assignments: "作业",
    gradingJobs: "批改任务",
    exports: "成绩导出",
    welcome: "欢迎回来",
    intro: "从创建作业开始，设置题目与评分标准。",
    createAssignment: "创建作业",
    emptyTitle: "还没有作业",
    emptyBody: "创建第一个作业，开始设置题目与评分标准。",
    teacher: "教师",
    accountTitle: "当前账户",
    accountRole: "角色：教师",
    accountBody: "账户管理将在阶段 3 接入。",
    collapse: "收起",
    expand: "展开",
    close: "关闭",
    createTitle: "创建新作业",
    createBody: "作业创建流程将在阶段 6 接入。",
    jobsTitle: "批改任务",
    jobsBody: "批量评分任务将在阶段 10 接入。",
    exportsTitle: "成绩导出",
    exportsBody: "成绩导出将在阶段 12 接入。",
    notFoundTitle: "页面不存在",
  },
  en: {
    mainNavigation: "Main navigation",
    assignments: "Assignments",
    gradingJobs: "Grading jobs",
    exports: "Grade exports",
    welcome: "Welcome back",
    intro: "Start by creating an assignment and defining its rubric.",
    createAssignment: "Create assignment",
    emptyTitle: "No assignments yet",
    emptyBody: "Create your first assignment to define the prompt and rubric.",
    teacher: "Teacher",
    accountTitle: "Current account",
    accountRole: "Role: Teacher",
    accountBody: "Account management will be connected in stage 3.",
    collapse: "Collapse",
    expand: "Expand",
    close: "Close",
    createTitle: "Create a new assignment",
    createBody: "The assignment workflow will be connected in stage 6.",
    jobsTitle: "Grading jobs",
    jobsBody: "Batch grading will be connected in stage 10.",
    exportsTitle: "Grade exports",
    exportsBody: "Grade exports will be connected in stage 12.",
    notFoundTitle: "Page not found",
  },
} as const;
