import type { Language } from "../../../app/copy";

export const providerCopy: Record<Language, Record<string, string>> = {
  zh: {
    title: "模型配置",
    intro: "配置评分模型供应商。Key 只会加密保存，页面不会回显。",
    add: "添加供应商",
    loading: "正在加载模型配置…",
    empty: "还没有供应商配置。",
    provider: "供应商",
    models: "允许模型",
    limits: "调用限制",
    state: "状态",
    actions: "操作",
    keyReady: "Key 已配置",
    keyMissing: "Key 未配置",
    tested: "当前配置已测试",
    untested: "当前配置未测试",
    draft: "草稿",
    enabled: "已启用",
    disabled: "已停用",
    edit: "编辑",
    test: "测试连接",
    enable: "启用",
    disable: "停用",
    testing: "测试中…",
    saving: "保存中…",
    working: "处理中…",
    createTitle: "添加模型供应商",
    editTitle: "编辑模型供应商",
    providerType: "供应商类型",
    name: "配置名称",
    baseUrl: "Base URL",
    apiKey: "API Key",
    apiKeyCreateHint: "仅在保存时发送一次。请勿粘贴到聊天或代码。",
    apiKeyEditHint: "留空会保留当前 Key，页面无法读取已保存的 Key。",
    allowedModels: "允许模型",
    allowedModelsHint: "每行一个模型，或用英文逗号分隔。",
    defaultModel: "默认模型",
    timeout: "超时秒数",
    concurrency: "最大并发",
    budget: "月预算（可选）",
    cancel: "取消",
    close: "关闭",
    save: "保存",
    loadFailed: "模型配置加载失败，请刷新页面重试。",
    saveFailed: "配置保存失败，页面内容未更改。",
    modelInvalid: "默认模型必须包含在允许模型中。",
    actionFailed: "操作失败，配置状态未更改。",
    testSucceeded: "连接测试通过。",
  },
  en: {
    title: "Model providers",
    intro: "Configure model providers for grading. Keys are encrypted and never shown again.",
    add: "Add provider",
    loading: "Loading model providers…",
    empty: "No model providers configured.",
    provider: "Provider",
    models: "Allowed models",
    limits: "Limits",
    state: "Status",
    actions: "Actions",
    keyReady: "Key configured",
    keyMissing: "Key missing",
    tested: "Current configuration tested",
    untested: "Current configuration not tested",
    draft: "Draft",
    enabled: "Enabled",
    disabled: "Disabled",
    edit: "Edit",
    test: "Test connection",
    enable: "Enable",
    disable: "Disable",
    testing: "Testing…",
    saving: "Saving…",
    working: "Working…",
    createTitle: "Add model provider",
    editTitle: "Edit model provider",
    providerType: "Provider type",
    name: "Configuration name",
    baseUrl: "Base URL",
    apiKey: "API Key",
    apiKeyCreateHint: "Sent once when saved. Never paste it into chat or source code.",
    apiKeyEditHint: "Leave blank to keep the current key. Saved keys cannot be read by this page.",
    allowedModels: "Allowed models",
    allowedModelsHint: "Enter one model per line, or separate them with commas.",
    defaultModel: "Default model",
    timeout: "Timeout in seconds",
    concurrency: "Maximum concurrency",
    budget: "Monthly budget (optional)",
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    loadFailed: "Model providers could not be loaded. Refresh and try again.",
    saveFailed: "The configuration was not saved.",
    modelInvalid: "The default model must be included in the allowed models.",
    actionFailed: "The action failed. The provider was not changed.",
    testSucceeded: "Connection test passed.",
  },
};
