export const exportsCopy = {
  zh: {
    title: "成绩导出",
    intro: "生成草稿或教师已确认的最终成绩工作簿。",
    create: "新建导出",
    chooseJob: "请先从批改任务选择一个批次。",
    backToJobs: "选择批改任务",
    paperCount: (count: number) => `${count} 篇论文`,
    sourceRange: (ai: number, draft: number, confirmed: number) =>
      `AI 建议 ${ai} · 教师草稿 ${draft} · 已确认 ${confirmed}`,
    exportType: "导出类型",
    draftGrade: "草稿成绩",
    draftHelp: "包含当前 AI 建议、教师草稿或已确认成绩，并明确标记为非最终成绩。",
    finalGrade: "最终成绩",
    finalHelp: "只包含全部由教师确认且批次已完成的最终成绩。",
    finalBlocked: (count: number) => `还有 ${count} 篇论文未由教师确认，不能生成最终成绩。`,
    draftBlocked: "该批次仍有未完成或没有成功评分结果的论文，不能生成草稿。",
    generateDraft: "生成草稿工作簿",
    generateFinal: "生成最终工作簿",
    generating: "正在创建…",
    createQueued: "导出已进入生成队列，页面会自动更新状态。",
    createFailed: "暂时无法创建导出，请检查批次状态后重试。",
    createUnauthorized: "登录已失效，请重新登录后再创建导出。",
    createNotFound: "无法访问该批次，请返回批改任务重新选择。",
    createConflict: "本次导出请求与先前请求不一致，请重新选择批次或类型。",
    history: "导出记录",
    loading: "正在加载导出记录…",
    loadFailed: "暂时无法加载导出记录。",
    loadUnauthorized: "登录已失效，请重新登录后再查看导出记录。",
    retryLoad: "重新加载",
    emptyTitle: "还没有导出记录",
    emptyBody: "从批改任务选择一个批次后，即可生成 Excel 工作簿。",
    assignment: "作业",
    batch: "批次",
    papers: "论文",
    created: "创建时间",
    draft: "草稿",
    final: "最终",
    queued: "等待生成",
    running: "生成中",
    completed: "已完成",
    failed: "失败",
    download: "下载",
    downloading: "正在获取下载地址…",
    downloadFailed: "无法获取新的下载地址，请稍后重试。",
  },
  en: {
    title: "Grade exports",
    intro: "Generate a draft workbook or a final workbook confirmed by the teacher.",
    create: "New export",
    chooseJob: "Choose a grading job before creating an export.",
    backToJobs: "Choose grading job",
    paperCount: (count: number) => `${count} papers`,
    sourceRange: (ai: number, draft: number, confirmed: number) =>
      `AI suggestions ${ai} · Teacher drafts ${draft} · Confirmed ${confirmed}`,
    exportType: "Export type",
    draftGrade: "Draft grades",
    draftHelp: "Includes the current AI suggestion, teacher draft, or confirmed grade and clearly marks every result as non-final.",
    finalGrade: "Final grades",
    finalHelp: "Includes only final grades from a completed job where every paper is teacher-confirmed.",
    finalBlocked: (count: number) => `${count} papers are not teacher-confirmed, so a final export is unavailable.`,
    draftBlocked: "This job still has unfinished papers or papers without a successful result, so a draft export is unavailable.",
    generateDraft: "Generate draft workbook",
    generateFinal: "Generate final workbook",
    generating: "Creating…",
    createQueued: "The export is queued. This page will update its status automatically.",
    createFailed: "The export could not be created. Check the job status and try again.",
    createUnauthorized: "Your session expired. Sign in again before creating an export.",
    createNotFound: "This grading job is unavailable. Return to grading jobs and choose it again.",
    createConflict: "This export request differs from the earlier request. Choose the job or type again.",
    history: "Export history",
    loading: "Loading exports…",
    loadFailed: "Exports could not be loaded.",
    loadUnauthorized: "Your session expired. Sign in again to view exports.",
    retryLoad: "Reload",
    emptyTitle: "No exports yet",
    emptyBody: "Choose a grading job to generate an Excel workbook.",
    assignment: "Assignment",
    batch: "Batch",
    papers: "Papers",
    created: "Created",
    draft: "Draft",
    final: "Final",
    queued: "Queued",
    running: "Running",
    completed: "Completed",
    failed: "Failed",
    download: "Download",
    downloading: "Getting download link…",
    downloadFailed: "A fresh download link could not be created. Try again.",
  },
} as const;
