export const authCopy = {
  zh: {
    loginTitle: "欢迎登录",
    loginSubtitle: "仅限受邀教师与管理员使用。",
    email: "邮箱",
    emailPlaceholder: "请输入邮箱",
    password: "密码",
    passwordPlaceholder: "请输入密码",
    invalidCredentials: "邮箱或密码错误，请重试。",
    signIn: "登录",
    signingIn: "正在登录…",
    forgotPassword: "忘记密码？",
    forgotTitle: "找回密码",
    forgotSubtitle: "输入受邀邮箱，我们会发送安全的重置链接。",
    resetFailed: "重置邮件发送失败，请稍后重试。",
    sendReset: "发送重置邮件",
    sendingReset: "正在发送…",
    resetSent: "如果邮箱已获邀请，你会收到密码重置邮件。",
    backToLogin: "返回登录",
    checkingLink: "正在验证安全链接…",
    expiredTitle: "链接已失效",
    expiredMessage: "邀请或重置链接无效或已过期，请重新申请。",
    firstPasswordTitle: "设置首次密码",
    newPasswordTitle: "设置新密码",
    passwordHint: "密码至少 8 位，保存后会进入 Paper Grading。",
    newPassword: "新密码",
    confirmPassword: "确认密码",
    passwordMismatch: "两次输入的密码不一致。",
    passwordSaveFailed: "密码保存失败，请重新打开邮件中的链接。",
    saveAndSignIn: "保存并登录",
    saving: "正在保存…",
  },
  en: {
    loginTitle: "Welcome back",
    loginSubtitle: "For invited teachers and administrators only.",
    email: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    invalidCredentials: "The email or password is incorrect.",
    signIn: "Sign in",
    signingIn: "Signing in…",
    forgotPassword: "Forgot password?",
    forgotTitle: "Reset password",
    forgotSubtitle: "Enter your invited email to receive a secure reset link.",
    resetFailed: "The reset email could not be sent. Please try again later.",
    sendReset: "Send reset email",
    sendingReset: "Sending…",
    resetSent: "If the email was invited, a password reset message is on its way.",
    backToLogin: "Back to sign in",
    checkingLink: "Checking the secure link…",
    expiredTitle: "Link expired",
    expiredMessage: "This invitation or reset link is invalid or expired. Request a new one.",
    firstPasswordTitle: "Create your password",
    newPasswordTitle: "Set a new password",
    passwordHint: "Use at least 8 characters. You will sign in after saving.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    passwordMismatch: "The passwords do not match.",
    passwordSaveFailed: "The password could not be saved. Open the email link again.",
    saveAndSignIn: "Save and sign in",
    saving: "Saving…",
  },
} as const;
